name: kk_flutter_ui_mvp
description: Minimal Material 3 UI prototype for Komoot Killer GPX route viewer.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/samples/
