// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<RouteAnalysisDto> parseGpxBytes(
        {required List<int> bytes, required String fallbackName}) =>
    RustLib.instance.api
        .crateApiParseGpxBytes(bytes: bytes, fallbackName: fallbackName);

class RouteAnalysisDto {
  final String name;
  final List<RoutePointDto> points;
  final double distanceKm;
  final double elevationGainM;
  final double elevationLossM;
  final double minElevationM;
  final double maxElevationM;
  final List<RouteSegmentDto> segments;
  final List<RouteWarningDto> warnings;

  const RouteAnalysisDto({
    required this.name,
    required this.points,
    required this.distanceKm,
    required this.elevationGainM,
    required this.elevationLossM,
    required this.minElevationM,
    required this.maxElevationM,
    required this.segments,
    required this.warnings,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      points.hashCode ^
      distanceKm.hashCode ^
      elevationGainM.hashCode ^
      elevationLossM.hashCode ^
      minElevationM.hashCode ^
      maxElevationM.hashCode ^
      segments.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteAnalysisDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          points == other.points &&
          distanceKm == other.distanceKm &&
          elevationGainM == other.elevationGainM &&
          elevationLossM == other.elevationLossM &&
          minElevationM == other.minElevationM &&
          maxElevationM == other.maxElevationM &&
          segments == other.segments &&
          warnings == other.warnings;
}

class RoutePointDto {
  final double lat;
  final double lon;
  final double elevationM;

  const RoutePointDto({
    required this.lat,
    required this.lon,
    required this.elevationM,
  });

  @override
  int get hashCode => lat.hashCode ^ lon.hashCode ^ elevationM.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutePointDto &&
          runtimeType == other.runtimeType &&
          lat == other.lat &&
          lon == other.lon &&
          elevationM == other.elevationM;
}

class RouteSegmentDto {
  final String title;
  final double distanceKm;
  final double elevationGainM;
  final String surfaceLabel;
  final String warningLevel;

  const RouteSegmentDto({
    required this.title,
    required this.distanceKm,
    required this.elevationGainM,
    required this.surfaceLabel,
    required this.warningLevel,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      distanceKm.hashCode ^
      elevationGainM.hashCode ^
      surfaceLabel.hashCode ^
      warningLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteSegmentDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          distanceKm == other.distanceKm &&
          elevationGainM == other.elevationGainM &&
          surfaceLabel == other.surfaceLabel &&
          warningLevel == other.warningLevel;
}

class RouteWarningDto {
  final String title;
  final String description;
  final String icon;

  const RouteWarningDto({
    required this.title,
    required this.description,
    required this.icon,
  });

  @override
  int get hashCode => title.hashCode ^ description.hashCode ^ icon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteWarningDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description &&
          icon == other.icon;
}
