// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -2139432152;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_core',
    ioDirectory: '../rust_core/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<RouteAnalysisDto> crateApiParseGpxBytes(
      {required List<int> bytes, required String fallbackName});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<RouteAnalysisDto> crateApiParseGpxBytes(
      {required List<int> bytes, required String fallbackName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_String(fallbackName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_route_analysis_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiParseGpxBytesConstMeta,
      argValues: [bytes, fallbackName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiParseGpxBytesConstMeta => const TaskConstMeta(
        debugName: "parse_gpx_bytes",
        argNames: ["bytes", "fallbackName"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RoutePointDto> dco_decode_list_route_point_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_route_point_dto).toList();
  }

  @protected
  List<RouteSegmentDto> dco_decode_list_route_segment_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_route_segment_dto).toList();
  }

  @protected
  List<RouteWarningDto> dco_decode_list_route_warning_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_route_warning_dto).toList();
  }

  @protected
  RouteAnalysisDto dco_decode_route_analysis_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return RouteAnalysisDto(
      name: dco_decode_String(arr[0]),
      points: dco_decode_list_route_point_dto(arr[1]),
      distanceKm: dco_decode_f_64(arr[2]),
      elevationGainM: dco_decode_f_64(arr[3]),
      elevationLossM: dco_decode_f_64(arr[4]),
      minElevationM: dco_decode_f_64(arr[5]),
      maxElevationM: dco_decode_f_64(arr[6]),
      segments: dco_decode_list_route_segment_dto(arr[7]),
      warnings: dco_decode_list_route_warning_dto(arr[8]),
    );
  }

  @protected
  RoutePointDto dco_decode_route_point_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RoutePointDto(
      lat: dco_decode_f_64(arr[0]),
      lon: dco_decode_f_64(arr[1]),
      elevationM: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  RouteSegmentDto dco_decode_route_segment_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RouteSegmentDto(
      title: dco_decode_String(arr[0]),
      distanceKm: dco_decode_f_64(arr[1]),
      elevationGainM: dco_decode_f_64(arr[2]),
      surfaceLabel: dco_decode_String(arr[3]),
      warningLevel: dco_decode_String(arr[4]),
    );
  }

  @protected
  RouteWarningDto dco_decode_route_warning_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RouteWarningDto(
      title: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      icon: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RoutePointDto> sse_decode_list_route_point_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RoutePointDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_route_point_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<RouteSegmentDto> sse_decode_list_route_segment_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RouteSegmentDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_route_segment_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<RouteWarningDto> sse_decode_list_route_warning_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RouteWarningDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_route_warning_dto(deserializer));
    }
    return ans_;
  }

  @protected
  RouteAnalysisDto sse_decode_route_analysis_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_points = sse_decode_list_route_point_dto(deserializer);
    var var_distanceKm = sse_decode_f_64(deserializer);
    var var_elevationGainM = sse_decode_f_64(deserializer);
    var var_elevationLossM = sse_decode_f_64(deserializer);
    var var_minElevationM = sse_decode_f_64(deserializer);
    var var_maxElevationM = sse_decode_f_64(deserializer);
    var var_segments = sse_decode_list_route_segment_dto(deserializer);
    var var_warnings = sse_decode_list_route_warning_dto(deserializer);
    return RouteAnalysisDto(
        name: var_name,
        points: var_points,
        distanceKm: var_distanceKm,
        elevationGainM: var_elevationGainM,
        elevationLossM: var_elevationLossM,
        minElevationM: var_minElevationM,
        maxElevationM: var_maxElevationM,
        segments: var_segments,
        warnings: var_warnings);
  }

  @protected
  RoutePointDto sse_decode_route_point_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lat = sse_decode_f_64(deserializer);
    var var_lon = sse_decode_f_64(deserializer);
    var var_elevationM = sse_decode_f_64(deserializer);
    return RoutePointDto(
        lat: var_lat, lon: var_lon, elevationM: var_elevationM);
  }

  @protected
  RouteSegmentDto sse_decode_route_segment_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_distanceKm = sse_decode_f_64(deserializer);
    var var_elevationGainM = sse_decode_f_64(deserializer);
    var var_surfaceLabel = sse_decode_String(deserializer);
    var var_warningLevel = sse_decode_String(deserializer);
    return RouteSegmentDto(
        title: var_title,
        distanceKm: var_distanceKm,
        elevationGainM: var_elevationGainM,
        surfaceLabel: var_surfaceLabel,
        warningLevel: var_warningLevel);
  }

  @protected
  RouteWarningDto sse_decode_route_warning_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_icon = sse_decode_String(deserializer);
    return RouteWarningDto(
        title: var_title, description: var_description, icon: var_icon);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_route_point_dto(
      List<RoutePointDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_route_point_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_route_segment_dto(
      List<RouteSegmentDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_route_segment_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_route_warning_dto(
      List<RouteWarningDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_route_warning_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_route_analysis_dto(
      RouteAnalysisDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_route_point_dto(self.points, serializer);
    sse_encode_f_64(self.distanceKm, serializer);
    sse_encode_f_64(self.elevationGainM, serializer);
    sse_encode_f_64(self.elevationLossM, serializer);
    sse_encode_f_64(self.minElevationM, serializer);
    sse_encode_f_64(self.maxElevationM, serializer);
    sse_encode_list_route_segment_dto(self.segments, serializer);
    sse_encode_list_route_warning_dto(self.warnings, serializer);
  }

  @protected
  void sse_encode_route_point_dto(
      RoutePointDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.lat, serializer);
    sse_encode_f_64(self.lon, serializer);
    sse_encode_f_64(self.elevationM, serializer);
  }

  @protected
  void sse_encode_route_segment_dto(
      RouteSegmentDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_f_64(self.distanceKm, serializer);
    sse_encode_f_64(self.elevationGainM, serializer);
    sse_encode_String(self.surfaceLabel, serializer);
    sse_encode_String(self.warningLevel, serializer);
  }

  @protected
  void sse_encode_route_warning_dto(
      RouteWarningDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.icon, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
