// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  List<OsmClassStatsDto> dco_decode_list_osm_class_stats_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RoutePartDto> dco_decode_list_route_part_dto(dynamic raw);

  @protected
  List<RoutePointDto> dco_decode_list_route_point_dto(dynamic raw);

  @protected
  List<RouteSegmentDto> dco_decode_list_route_segment_dto(dynamic raw);

  @protected
  List<RouteWarningDto> dco_decode_list_route_warning_dto(dynamic raw);

  @protected
  OsmClassStatsDto dco_decode_osm_class_stats_dto(dynamic raw);

  @protected
  OsmImportReportDto dco_decode_osm_import_report_dto(dynamic raw);

  @protected
  OsmPackBuildDto dco_decode_osm_pack_build_dto(dynamic raw);

  @protected
  OsmPackStatsDto dco_decode_osm_pack_stats_dto(dynamic raw);

  @protected
  RouteAnalysisDto dco_decode_route_analysis_dto(dynamic raw);

  @protected
  RouteBoundsDto dco_decode_route_bounds_dto(dynamic raw);

  @protected
  RoutePartDto dco_decode_route_part_dto(dynamic raw);

  @protected
  RoutePointDto dco_decode_route_point_dto(dynamic raw);

  @protected
  RouteSegmentDto dco_decode_route_segment_dto(dynamic raw);

  @protected
  RouteWarningDto dco_decode_route_warning_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  List<OsmClassStatsDto> sse_decode_list_osm_class_stats_dto(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RoutePartDto> sse_decode_list_route_part_dto(
      SseDeserializer deserializer);

  @protected
  List<RoutePointDto> sse_decode_list_route_point_dto(
      SseDeserializer deserializer);

  @protected
  List<RouteSegmentDto> sse_decode_list_route_segment_dto(
      SseDeserializer deserializer);

  @protected
  List<RouteWarningDto> sse_decode_list_route_warning_dto(
      SseDeserializer deserializer);

  @protected
  OsmClassStatsDto sse_decode_osm_class_stats_dto(SseDeserializer deserializer);

  @protected
  OsmImportReportDto sse_decode_osm_import_report_dto(
      SseDeserializer deserializer);

  @protected
  OsmPackBuildDto sse_decode_osm_pack_build_dto(SseDeserializer deserializer);

  @protected
  OsmPackStatsDto sse_decode_osm_pack_stats_dto(SseDeserializer deserializer);

  @protected
  RouteAnalysisDto sse_decode_route_analysis_dto(SseDeserializer deserializer);

  @protected
  RouteBoundsDto sse_decode_route_bounds_dto(SseDeserializer deserializer);

  @protected
  RoutePartDto sse_decode_route_part_dto(SseDeserializer deserializer);

  @protected
  RoutePointDto sse_decode_route_point_dto(SseDeserializer deserializer);

  @protected
  RouteSegmentDto sse_decode_route_segment_dto(SseDeserializer deserializer);

  @protected
  RouteWarningDto sse_decode_route_warning_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_osm_class_stats_dto(
      List<OsmClassStatsDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_route_part_dto(
      List<RoutePartDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_route_point_dto(
      List<RoutePointDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_route_segment_dto(
      List<RouteSegmentDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_route_warning_dto(
      List<RouteWarningDto> self, SseSerializer serializer);

  @protected
  void sse_encode_osm_class_stats_dto(
      OsmClassStatsDto self, SseSerializer serializer);

  @protected
  void sse_encode_osm_import_report_dto(
      OsmImportReportDto self, SseSerializer serializer);

  @protected
  void sse_encode_osm_pack_build_dto(
      OsmPackBuildDto self, SseSerializer serializer);

  @protected
  void sse_encode_osm_pack_stats_dto(
      OsmPackStatsDto self, SseSerializer serializer);

  @protected
  void sse_encode_route_analysis_dto(
      RouteAnalysisDto self, SseSerializer serializer);

  @protected
  void sse_encode_route_bounds_dto(
      RouteBoundsDto self, SseSerializer serializer);

  @protected
  void sse_encode_route_part_dto(RoutePartDto self, SseSerializer serializer);

  @protected
  void sse_encode_route_point_dto(RoutePointDto self, SseSerializer serializer);

  @protected
  void sse_encode_route_segment_dto(
      RouteSegmentDto self, SseSerializer serializer);

  @protected
  void sse_encode_route_warning_dto(
      RouteWarningDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
