// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1456397213;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_core',
    ioDirectory: '../rust_core/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<OsmPackBuildDto> crateApiBuildOsmPackBytesFromPbf(
      {required List<int> bytes, required String sourceName});

  Future<OsmPackStatsDto> crateApiBuildOsmPackStatsFromPbfPath(
      {required String path, required String sourceName});

  Future<OsmPackStatsDto> crateApiInspectKkosmBytes({required List<int> bytes});

  Future<OsmPackStatsDto> crateApiInspectKkosmPath({required String path});

  Future<RouteAnalysisDto> crateApiParseGpxBytes(
      {required List<int> bytes, required String fallbackName});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<OsmPackBuildDto> crateApiBuildOsmPackBytesFromPbf(
      {required List<int> bytes, required String sourceName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_String(sourceName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_osm_pack_build_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBuildOsmPackBytesFromPbfConstMeta,
      argValues: [bytes, sourceName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBuildOsmPackBytesFromPbfConstMeta =>
      const TaskConstMeta(
        debugName: "build_osm_pack_bytes_from_pbf",
        argNames: ["bytes", "sourceName"],
      );

  @override
  Future<OsmPackStatsDto> crateApiBuildOsmPackStatsFromPbfPath(
      {required String path, required String sourceName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(sourceName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_osm_pack_stats_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBuildOsmPackStatsFromPbfPathConstMeta,
      argValues: [path, sourceName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBuildOsmPackStatsFromPbfPathConstMeta =>
      const TaskConstMeta(
        debugName: "build_osm_pack_stats_from_pbf_path",
        argNames: ["path", "sourceName"],
      );

  @override
  Future<OsmPackStatsDto> crateApiInspectKkosmBytes(
      {required List<int> bytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_osm_pack_stats_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInspectKkosmBytesConstMeta,
      argValues: [bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInspectKkosmBytesConstMeta => const TaskConstMeta(
        debugName: "inspect_kkosm_bytes",
        argNames: ["bytes"],
      );

  @override
  Future<OsmPackStatsDto> crateApiInspectKkosmPath({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_osm_pack_stats_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInspectKkosmPathConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInspectKkosmPathConstMeta => const TaskConstMeta(
        debugName: "inspect_kkosm_path",
        argNames: ["path"],
      );

  @override
  Future<RouteAnalysisDto> crateApiParseGpxBytes(
      {required List<int> bytes, required String fallbackName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_String(fallbackName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_route_analysis_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiParseGpxBytesConstMeta,
      argValues: [bytes, fallbackName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiParseGpxBytesConstMeta => const TaskConstMeta(
        debugName: "parse_gpx_bytes",
        argNames: ["bytes", "fallbackName"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<OsmClassStatsDto> dco_decode_list_osm_class_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_osm_class_stats_dto).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RoutePartDto> dco_decode_list_route_part_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_route_part_dto).toList();
  }

  @protected
  List<RoutePointDto> dco_decode_list_route_point_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_route_point_dto).toList();
  }

  @protected
  List<RouteSegmentDto> dco_decode_list_route_segment_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_route_segment_dto).toList();
  }

  @protected
  List<RouteWarningDto> dco_decode_list_route_warning_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_route_warning_dto).toList();
  }

  @protected
  OsmClassStatsDto dco_decode_osm_class_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OsmClassStatsDto(
      className: dco_decode_String(arr[0]),
      segments: dco_decode_u_32(arr[1]),
      lengthKm: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  OsmImportReportDto dco_decode_osm_import_report_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return OsmImportReportDto(
      source: dco_decode_String(arr[0]),
      highwayWays: dco_decode_u_32(arr[1]),
      roadSegments: dco_decode_u_32(arr[2]),
      skippedDegenerateSegments: dco_decode_u_32(arr[3]),
      skippedMissingNodes: dco_decode_u_32(arr[4]),
      totalLengthKm: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  OsmPackBuildDto dco_decode_osm_pack_build_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OsmPackBuildDto(
      packBytes: dco_decode_list_prim_u_8_strict(arr[0]),
      stats: dco_decode_osm_pack_stats_dto(arr[1]),
      report: dco_decode_osm_import_report_dto(arr[2]),
    );
  }

  @protected
  OsmPackStatsDto dco_decode_osm_pack_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return OsmPackStatsDto(
      source: dco_decode_String(arr[0]),
      formatVersion: dco_decode_u_32(arr[1]),
      roadSegments: dco_decode_u_32(arr[2]),
      totalLengthKm: dco_decode_f_64(arr[3]),
      byHighway: dco_decode_list_osm_class_stats_dto(arr[4]),
      bySurface: dco_decode_list_osm_class_stats_dto(arr[5]),
    );
  }

  @protected
  RouteAnalysisDto dco_decode_route_analysis_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return RouteAnalysisDto(
      name: dco_decode_String(arr[0]),
      points: dco_decode_list_route_point_dto(arr[1]),
      distanceKm: dco_decode_f_64(arr[2]),
      elevationGainM: dco_decode_f_64(arr[3]),
      elevationLossM: dco_decode_f_64(arr[4]),
      minElevationM: dco_decode_f_64(arr[5]),
      maxElevationM: dco_decode_f_64(arr[6]),
      bounds: dco_decode_route_bounds_dto(arr[7]),
      parts: dco_decode_list_route_part_dto(arr[8]),
      segments: dco_decode_list_route_segment_dto(arr[9]),
      warnings: dco_decode_list_route_warning_dto(arr[10]),
    );
  }

  @protected
  RouteBoundsDto dco_decode_route_bounds_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RouteBoundsDto(
      minLat: dco_decode_f_64(arr[0]),
      minLon: dco_decode_f_64(arr[1]),
      maxLat: dco_decode_f_64(arr[2]),
      maxLon: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  RoutePartDto dco_decode_route_part_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RoutePartDto(
      index: dco_decode_u_32(arr[0]),
      startIndex: dco_decode_u_32(arr[1]),
      endIndex: dco_decode_u_32(arr[2]),
      pointCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  RoutePointDto dco_decode_route_point_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RoutePointDto(
      lat: dco_decode_f_64(arr[0]),
      lon: dco_decode_f_64(arr[1]),
      elevationM: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  RouteSegmentDto dco_decode_route_segment_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RouteSegmentDto(
      title: dco_decode_String(arr[0]),
      distanceKm: dco_decode_f_64(arr[1]),
      elevationGainM: dco_decode_f_64(arr[2]),
      surfaceLabel: dco_decode_String(arr[3]),
      warningLevel: dco_decode_String(arr[4]),
    );
  }

  @protected
  RouteWarningDto dco_decode_route_warning_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RouteWarningDto(
      title: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      icon: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<OsmClassStatsDto> sse_decode_list_osm_class_stats_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OsmClassStatsDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_osm_class_stats_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RoutePartDto> sse_decode_list_route_part_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RoutePartDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_route_part_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<RoutePointDto> sse_decode_list_route_point_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RoutePointDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_route_point_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<RouteSegmentDto> sse_decode_list_route_segment_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RouteSegmentDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_route_segment_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<RouteWarningDto> sse_decode_list_route_warning_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RouteWarningDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_route_warning_dto(deserializer));
    }
    return ans_;
  }

  @protected
  OsmClassStatsDto sse_decode_osm_class_stats_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_className = sse_decode_String(deserializer);
    var var_segments = sse_decode_u_32(deserializer);
    var var_lengthKm = sse_decode_f_64(deserializer);
    return OsmClassStatsDto(
        className: var_className,
        segments: var_segments,
        lengthKm: var_lengthKm);
  }

  @protected
  OsmImportReportDto sse_decode_osm_import_report_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_source = sse_decode_String(deserializer);
    var var_highwayWays = sse_decode_u_32(deserializer);
    var var_roadSegments = sse_decode_u_32(deserializer);
    var var_skippedDegenerateSegments = sse_decode_u_32(deserializer);
    var var_skippedMissingNodes = sse_decode_u_32(deserializer);
    var var_totalLengthKm = sse_decode_f_64(deserializer);
    return OsmImportReportDto(
        source: var_source,
        highwayWays: var_highwayWays,
        roadSegments: var_roadSegments,
        skippedDegenerateSegments: var_skippedDegenerateSegments,
        skippedMissingNodes: var_skippedMissingNodes,
        totalLengthKm: var_totalLengthKm);
  }

  @protected
  OsmPackBuildDto sse_decode_osm_pack_build_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_packBytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_stats = sse_decode_osm_pack_stats_dto(deserializer);
    var var_report = sse_decode_osm_import_report_dto(deserializer);
    return OsmPackBuildDto(
        packBytes: var_packBytes, stats: var_stats, report: var_report);
  }

  @protected
  OsmPackStatsDto sse_decode_osm_pack_stats_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_source = sse_decode_String(deserializer);
    var var_formatVersion = sse_decode_u_32(deserializer);
    var var_roadSegments = sse_decode_u_32(deserializer);
    var var_totalLengthKm = sse_decode_f_64(deserializer);
    var var_byHighway = sse_decode_list_osm_class_stats_dto(deserializer);
    var var_bySurface = sse_decode_list_osm_class_stats_dto(deserializer);
    return OsmPackStatsDto(
        source: var_source,
        formatVersion: var_formatVersion,
        roadSegments: var_roadSegments,
        totalLengthKm: var_totalLengthKm,
        byHighway: var_byHighway,
        bySurface: var_bySurface);
  }

  @protected
  RouteAnalysisDto sse_decode_route_analysis_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_points = sse_decode_list_route_point_dto(deserializer);
    var var_distanceKm = sse_decode_f_64(deserializer);
    var var_elevationGainM = sse_decode_f_64(deserializer);
    var var_elevationLossM = sse_decode_f_64(deserializer);
    var var_minElevationM = sse_decode_f_64(deserializer);
    var var_maxElevationM = sse_decode_f_64(deserializer);
    var var_bounds = sse_decode_route_bounds_dto(deserializer);
    var var_parts = sse_decode_list_route_part_dto(deserializer);
    var var_segments = sse_decode_list_route_segment_dto(deserializer);
    var var_warnings = sse_decode_list_route_warning_dto(deserializer);
    return RouteAnalysisDto(
        name: var_name,
        points: var_points,
        distanceKm: var_distanceKm,
        elevationGainM: var_elevationGainM,
        elevationLossM: var_elevationLossM,
        minElevationM: var_minElevationM,
        maxElevationM: var_maxElevationM,
        bounds: var_bounds,
        parts: var_parts,
        segments: var_segments,
        warnings: var_warnings);
  }

  @protected
  RouteBoundsDto sse_decode_route_bounds_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_minLat = sse_decode_f_64(deserializer);
    var var_minLon = sse_decode_f_64(deserializer);
    var var_maxLat = sse_decode_f_64(deserializer);
    var var_maxLon = sse_decode_f_64(deserializer);
    return RouteBoundsDto(
        minLat: var_minLat,
        minLon: var_minLon,
        maxLat: var_maxLat,
        maxLon: var_maxLon);
  }

  @protected
  RoutePartDto sse_decode_route_part_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_startIndex = sse_decode_u_32(deserializer);
    var var_endIndex = sse_decode_u_32(deserializer);
    var var_pointCount = sse_decode_u_32(deserializer);
    return RoutePartDto(
        index: var_index,
        startIndex: var_startIndex,
        endIndex: var_endIndex,
        pointCount: var_pointCount);
  }

  @protected
  RoutePointDto sse_decode_route_point_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lat = sse_decode_f_64(deserializer);
    var var_lon = sse_decode_f_64(deserializer);
    var var_elevationM = sse_decode_f_64(deserializer);
    return RoutePointDto(
        lat: var_lat, lon: var_lon, elevationM: var_elevationM);
  }

  @protected
  RouteSegmentDto sse_decode_route_segment_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_distanceKm = sse_decode_f_64(deserializer);
    var var_elevationGainM = sse_decode_f_64(deserializer);
    var var_surfaceLabel = sse_decode_String(deserializer);
    var var_warningLevel = sse_decode_String(deserializer);
    return RouteSegmentDto(
        title: var_title,
        distanceKm: var_distanceKm,
        elevationGainM: var_elevationGainM,
        surfaceLabel: var_surfaceLabel,
        warningLevel: var_warningLevel);
  }

  @protected
  RouteWarningDto sse_decode_route_warning_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_icon = sse_decode_String(deserializer);
    return RouteWarningDto(
        title: var_title, description: var_description, icon: var_icon);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_osm_class_stats_dto(
      List<OsmClassStatsDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_osm_class_stats_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_route_part_dto(
      List<RoutePartDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_route_part_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_route_point_dto(
      List<RoutePointDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_route_point_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_route_segment_dto(
      List<RouteSegmentDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_route_segment_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_route_warning_dto(
      List<RouteWarningDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_route_warning_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_osm_class_stats_dto(
      OsmClassStatsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.className, serializer);
    sse_encode_u_32(self.segments, serializer);
    sse_encode_f_64(self.lengthKm, serializer);
  }

  @protected
  void sse_encode_osm_import_report_dto(
      OsmImportReportDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.source, serializer);
    sse_encode_u_32(self.highwayWays, serializer);
    sse_encode_u_32(self.roadSegments, serializer);
    sse_encode_u_32(self.skippedDegenerateSegments, serializer);
    sse_encode_u_32(self.skippedMissingNodes, serializer);
    sse_encode_f_64(self.totalLengthKm, serializer);
  }

  @protected
  void sse_encode_osm_pack_build_dto(
      OsmPackBuildDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.packBytes, serializer);
    sse_encode_osm_pack_stats_dto(self.stats, serializer);
    sse_encode_osm_import_report_dto(self.report, serializer);
  }

  @protected
  void sse_encode_osm_pack_stats_dto(
      OsmPackStatsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.source, serializer);
    sse_encode_u_32(self.formatVersion, serializer);
    sse_encode_u_32(self.roadSegments, serializer);
    sse_encode_f_64(self.totalLengthKm, serializer);
    sse_encode_list_osm_class_stats_dto(self.byHighway, serializer);
    sse_encode_list_osm_class_stats_dto(self.bySurface, serializer);
  }

  @protected
  void sse_encode_route_analysis_dto(
      RouteAnalysisDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_route_point_dto(self.points, serializer);
    sse_encode_f_64(self.distanceKm, serializer);
    sse_encode_f_64(self.elevationGainM, serializer);
    sse_encode_f_64(self.elevationLossM, serializer);
    sse_encode_f_64(self.minElevationM, serializer);
    sse_encode_f_64(self.maxElevationM, serializer);
    sse_encode_route_bounds_dto(self.bounds, serializer);
    sse_encode_list_route_part_dto(self.parts, serializer);
    sse_encode_list_route_segment_dto(self.segments, serializer);
    sse_encode_list_route_warning_dto(self.warnings, serializer);
  }

  @protected
  void sse_encode_route_bounds_dto(
      RouteBoundsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.minLat, serializer);
    sse_encode_f_64(self.minLon, serializer);
    sse_encode_f_64(self.maxLat, serializer);
    sse_encode_f_64(self.maxLon, serializer);
  }

  @protected
  void sse_encode_route_part_dto(RoutePartDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_u_32(self.startIndex, serializer);
    sse_encode_u_32(self.endIndex, serializer);
    sse_encode_u_32(self.pointCount, serializer);
  }

  @protected
  void sse_encode_route_point_dto(
      RoutePointDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.lat, serializer);
    sse_encode_f_64(self.lon, serializer);
    sse_encode_f_64(self.elevationM, serializer);
  }

  @protected
  void sse_encode_route_segment_dto(
      RouteSegmentDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_f_64(self.distanceKm, serializer);
    sse_encode_f_64(self.elevationGainM, serializer);
    sse_encode_String(self.surfaceLabel, serializer);
    sse_encode_String(self.warningLevel, serializer);
  }

  @protected
  void sse_encode_route_warning_dto(
      RouteWarningDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.icon, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
